In [21]:
!pip install h5py
import h5py
import numpy as np

In [22]:
f = h5py.File('/home/fernando/home_temp/CA1__/data-bbp/20191017/sonata/nodes/nodes.h5', 'r')

In [23]:
f['nodes']['hippocampus_neurons']['0']['synapse_class'][35:37]

array([1, 0], dtype=uint32)

In [24]:
list(f['nodes'])

['hippocampus_neurons', 'hippocampus_projections']

In [25]:
list(f['nodes']['hippocampus_neurons']['0']['@library'])

['etype', 'model_type', 'morph_class', 'morphology', 'mtype', 'synapse_class']

In [26]:
f = h5py.File('/home/fernando/home_temp/CA1__/data-bbp/20191017/sonata/nodes/nodes_hippocampus.h5', 'r')

In [33]:
gid_list = [18097, 18109, 18140, 18149, 18163, 18177,18189, 18191, 16950, 16963, 17199, 17202, 
						17411, 17416, 17486, 17497, 13513, 14311, 17946, 17958, 22, 25, 1, 3]
gid_list = gid_list - np.ones_like(gid_list) # start from 1 in original list

In [35]:
for gid in gid_list:
    print(f['nodes']['hippocampus_neurons']['0']['model_template'][gid],
#          f['nodes']['hippocampus_neurons']['0']['morphology'][gid],
          f['nodes']['hippocampus_neurons']['0']['mtype'][gid]
#          f['nodes']['hippocampus_neurons']['0']['etype'][gid],
#           f['nodes']['hippocampus_neurons']['0']['synapse_class'][gid]
         )

b'hoc:CA1_int_cAC_011017HP2_2019032814552' 3
b'hoc:CA1_int_cAC_011017HP2_2019032814552' 3
b'hoc:CA1_int_cNAC_970911C_2019030512040' 2
b'hoc:CA1_int_cNAC_970509HP2_2019030511562' 2
b'hoc:CA1_int_cAC_011017HP2_2019032814552' 4
b'hoc:CA1_int_cAC_980120A_2019032816092' 4
b'hoc:CA1_int_cNAC_980120A_2019032915503' 1
b'hoc:CA1_int_cNAC_971114B_2019032915460' 1
b'hoc:CA1_int_bAC_971114B_2019032912011' 10
b'hoc:CA1_int_cNAC_060314AM2_2019032816533' 10
b'hoc:CA1_int_cAC_031031AM1_2019032815001' 7
b'hoc:CA1_int_cAC_031031AM1_2019032815001' 7
b'hoc:CA1_int_cNAC_990111HP2_2019032915570' 6
b'hoc:CA1_int_cNAC_971114B_2019032915460' 6
b'hoc:CA1_int_bAC_971114B_2019032912011' 5
b'hoc:CA1_int_bAC_971114B_2019032912011' 5
b'hoc:CA1_pyr_cACpyr_mpg141017_a1_2_idC_2019032814340' 9
b'hoc:CA1_pyr_cACpyr_oh140807_A0_idF_2019030511545' 9
b'hoc:CA1_int_cNAC_980513B_2019032915552' 8
b'hoc:CA1_int_bAC_971114B_2019032912011' 8
b'hoc:CA1_int_cAC_990611HP2_2019032816214' 11
b'hoc:CA1_int_cAC_990611HP2_2019032816214' 

In [36]:
gid = 18041
print(f['nodes']['hippocampus_neurons']['0']['model_template'][gid],
      f['nodes']['hippocampus_neurons']['0']['mtype'][gid])

b'hoc:CA1_int_cAC_011017HP2_2019032814552' 3


In [9]:
f = h5py.File('/home/fernando/home_temp/CA1__/data-bbp/20191017/sonata/edges/edges.h5', 'r')

In [10]:
list(f['edges']['hippocampus_neurons__hippocampus_neurons__chemical'])

['0', 'edge_type_id', 'indices', 'source_node_id', 'target_node_id']

In [11]:
list(f['edges']['hippocampus_neurons__hippocampus_neurons__chemical']['source_node_id'][0:30])

[18041,
 18041,
 18041,
 18041,
 18041,
 18041,
 18041,
 18041,
 18069,
 18069,
 18069,
 18081,
 18081,
 18081,
 18081,
 18091,
 18091,
 18091,
 18095,
 18095,
 18095,
 18095,
 18115,
 18115,
 18145,
 6,
 9,
 17703,
 18005,
 18040]

In [12]:
list(f['edges']['hippocampus_neurons__hippocampus_neurons__chemical']['target_node_id'][0:30])

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1]

In [13]:
list(f['edges']['hippocampus_neurons__hippocampus_neurons__chemical']['indices']['target_to_source']['range_to_edge_id'])

[array([ 0, 25], dtype=uint64),
 array([25, 48], dtype=uint64),
 array([48, 78], dtype=uint64),
 array([  78, 1181], dtype=uint64),
 array([1181, 3592], dtype=uint64),
 array([3592, 4650], dtype=uint64),
 array([4650, 5615], dtype=uint64),
 array([5615, 8041], dtype=uint64),
 array([ 8041, 10224], dtype=uint64),
 array([10224, 12199], dtype=uint64),
 array([12199, 15864], dtype=uint64),
 array([15864, 17717], dtype=uint64),
 array([17717, 20346], dtype=uint64),
 array([20346, 23785], dtype=uint64),
 array([23785, 25485], dtype=uint64),
 array([25485, 27042], dtype=uint64),
 array([27042, 29621], dtype=uint64),
 array([29621, 31531], dtype=uint64),
 array([31531, 33675], dtype=uint64),
 array([33675, 35356], dtype=uint64),
 array([35356, 37138], dtype=uint64),
 array([37138, 40679], dtype=uint64),
 array([40679, 43232], dtype=uint64),
 array([43232, 44196], dtype=uint64),
 array([44196, 47033], dtype=uint64),
 array([47033, 49705], dtype=uint64),
 array([49705, 51429], dtype=uint64),
 a

In [14]:
list(f['edges']['hippocampus_neurons__hippocampus_neurons__chemical']['indices']['target_to_source']['node_id_to_ranges'])

[array([0, 1], dtype=uint64),
 array([1, 2], dtype=uint64),
 array([2, 3], dtype=uint64),
 array([3, 4], dtype=uint64),
 array([4, 5], dtype=uint64),
 array([5, 6], dtype=uint64),
 array([6, 7], dtype=uint64),
 array([7, 8], dtype=uint64),
 array([8, 9], dtype=uint64),
 array([ 9, 10], dtype=uint64),
 array([10, 11], dtype=uint64),
 array([11, 12], dtype=uint64),
 array([12, 13], dtype=uint64),
 array([13, 14], dtype=uint64),
 array([14, 15], dtype=uint64),
 array([15, 16], dtype=uint64),
 array([16, 17], dtype=uint64),
 array([17, 18], dtype=uint64),
 array([18, 19], dtype=uint64),
 array([19, 20], dtype=uint64),
 array([20, 21], dtype=uint64),
 array([21, 22], dtype=uint64),
 array([22, 23], dtype=uint64),
 array([23, 24], dtype=uint64),
 array([24, 25], dtype=uint64),
 array([25, 26], dtype=uint64),
 array([26, 27], dtype=uint64),
 array([27, 28], dtype=uint64),
 array([28, 29], dtype=uint64),
 array([29, 30], dtype=uint64),
 array([30, 31], dtype=uint64),
 array([31, 32], dtype=uin

In [15]:
list(f['edges']['hippocampus_neurons__hippocampus_neurons__chemical']['indices']['source_to_target']['node_id_to_ranges'])

[array([  0, 576], dtype=uint64),
 array([ 576, 1206], dtype=uint64),
 array([1206, 1719], dtype=uint64),
 array([1719, 2353], dtype=uint64),
 array([2353, 3621], dtype=uint64),
 array([3621, 4695], dtype=uint64),
 array([4695, 5851], dtype=uint64),
 array([5851, 7152], dtype=uint64),
 array([7152, 7603], dtype=uint64),
 array([7603, 9000], dtype=uint64),
 array([ 9000, 10276], dtype=uint64),
 array([10276, 10856], dtype=uint64),
 array([10856, 11251], dtype=uint64),
 array([11251, 12587], dtype=uint64),
 array([12587, 12938], dtype=uint64),
 array([12938, 13518], dtype=uint64),
 array([13518, 13887], dtype=uint64),
 array([13887, 14083], dtype=uint64),
 array([14083, 15406], dtype=uint64),
 array([15406, 16461], dtype=uint64),
 array([16461, 17688], dtype=uint64),
 array([17688, 18656], dtype=uint64),
 array([18656, 19535], dtype=uint64),
 array([19535, 20279], dtype=uint64),
 array([20279, 21589], dtype=uint64),
 array([21589, 22665], dtype=uint64),
 array([22665, 23780], dtype=uint6

In [16]:
list(f['edges']['hippocampus_neurons__hippocampus_neurons__chemical']['0'])

['afferent_center_x',
 'afferent_center_y',
 'afferent_center_z',
 'afferent_section_id',
 'afferent_section_pos',
 'afferent_section_pos_orig',
 'afferent_section_type',
 'afferent_segment_id',
 'afferent_segment_offset',
 'conductance',
 'decay_time',
 'delay',
 'depression_time',
 'efferent_section_id',
 'efferent_section_pos',
 'efferent_section_pos_orig',
 'efferent_section_type',
 'efferent_segment_id',
 'efferent_segment_offset',
 'efferent_surface_x',
 'efferent_surface_y',
 'efferent_surface_z',
 'facilitation_time',
 'n_rrp_vesicles',
 'spine_length',
 'syn_type_id',
 'synapse_type_id',
 'u_syn']

In [17]:
list(f['edges']['hippocampus_neurons__hippocampus_neurons__chemical']['0']['conductance'][0:100])

[2.0207853,
 2.0207853,
 2.0207853,
 2.0207853,
 2.0207853,
 2.0207853,
 2.0207853,
 2.0207853,
 1.963498,
 1.963498,
 1.963498,
 2.084363,
 2.084363,
 2.084363,
 2.084363,
 2.0013206,
 2.0013206,
 2.0013206,
 2.8237672,
 2.8237672,
 2.8237672,
 2.8237672,
 2.2224798,
 2.2224798,
 1.9513471,
 2.1065934,
 2.213616,
 2.4385297,
 1.8306538,
 2.2212687,
 2.2212687,
 2.2212687,
 1.9028753,
 1.9028753,
 1.9028753,
 1.9028753,
 1.9028753,
 1.9028753,
 1.9333199,
 1.9333199,
 1.9333199,
 1.9333199,
 2.0619507,
 2.0619507,
 2.1538668,
 2.1538668,
 2.1538668,
 2.1538668,
 1.9009407,
 1.9009407,
 1.7967001,
 1.8814647,
 1.8814647,
 1.8814647,
 1.8814647,
 1.8814647,
 1.8814647,
 1.80009,
 1.80009,
 1.80009,
 1.80009,
 1.80009,
 2.1981578,
 2.1981578,
 2.1981578,
 2.1981578,
 2.1485407,
 2.1485407,
 2.1485407,
 2.1485407,
 2.1485407,
 2.1485407,
 2.1485407,
 2.1485407,
 2.1485407,
 2.1485407,
 2.3526645,
 3.4147098,
 1.8284684,
 1.8284684,
 1.8284684,
 2.7065952,
 2.7065952,
 3.511927,
 3.511927,


In [18]:
list(f['edges']['hippocampus_neurons__hippocampus_neurons__chemical']['0']['syn_type_id'][50:150])

[7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102,
 102]